
-- create
CREATE TABLE ADDRESS(
  AID INTEGER PRIMARY KEY,
  BLOCK VARCHAR(10) NOT NULL,
  STREET VARCHAR(25) NOT NULL,
  LOCALITY VARCHAR(30) ,
  CITY VARCHAR(25) NOT NULL,
  PINCODE INTEGER NOT NULL CHECK(PINCODE <= 999999 AND PINCODE >=100000),
  STATE VARCHAR(25) NOT NULL,
  COUNTRY VARCHAR(25) NOT NULL
);

CREATE TABLE SEASON (
  seid INTEGER PRIMARY KEY,
  name VARCHAR(10) NOT NULL
);
CREATE TABLE EMPLOYEE (
  EID INTEGER PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  MNO INTEGER NOT NULL,
  SALARY INTEGER NOT NULL,
  AID INTEGER references ADDRESS(AID) 
);


CREATE TABLE TOOLS(
  TID INTEGER PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  mode boolean not NULL,
  price INTEGER not NULL
);


CREATE TABLE PRODUCT(
  PID INTEGER PRIMARY KEY,
  SEID INTEGER references SEASON(SEID)
);
CREATE TABLE DISEASE(
  DID INTEGER PRIMARY KEY,
  NAME VARCHAR(25) NOT NULL,
  PID INTEGER references PRODUCT(PID) NOT NULL
);

CREATE TABLE MEDICINE(
  NAME VARCHAR(25) NOT NULL,
  COST INTEGER NOT NULL,
  COMPANY VARCHAR(25) NOT NULL,
  DID INTEGER references DISEASE(DID)
);


CREATE TABLE FRUITS(
  PID INTEGER references PRODUCT(PID) PRIMARY KEY,
  NAME VARCHAR(25) NOT NULL,
  SEID INTEGER references SEASON(SEID)
);

CREATE TABLE FLOWERS(
  PID INTEGER references PRODUCT(PID) PRIMARY KEY,
  NAME VARCHAR(25) NOT NULL,
  HABITATE VARCHAR(10) NOT NULL,
  SEID INTEGER references SEASON(SEID) NOT NULL
);

CREATE TABLE BERRIES(
  PID INTEGER references PRODUCT(PID) PRIMARY KEY,
  NAME VARCHAR(25) NOT NULL,
  SEID INTEGER references SEASON(SEID) NOT NULL
);

 
 
CREATE TABLE MANAGER(
  MID INTEGER references EMPLOYEE(EID) PRIMARY KEY
);
 
CREATE TABLE MANAGES( 
  MID INTEGER references MANAGER(MID) NOT NULL,
  PID INTEGER references PRODUCT(PID) NOT NULL
);

CREATE TABLE CUSTOMER(
  CID INTEGER PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  AID INTEGER references ADDRESS(AID) NOT NULL
);

CREATE TABLE USED_FOR(
  TID INTEGER references TOOLS(TID) NOT NULL,
  PID INTEGER references PRODUCT(PID) NOT NULL
);

CREATE TABLE GARDEN_OWNERS(
  GID INTEGER PRIMARY KEY,
  NAME VARCHAR(30) NOT NULL,
  number char(10) NOT NULL CHECK(LENGTH(number) =10),
  DURATION INTEGER NOT NULL CHECK(DURATION >0  AND DURATION <11),
  AREA numeric(6,2) NOT NULL CHECK (AREA > 0),
  CHARGEPERMONTH INTEGER NOT NULL CHECK(CHARGEPERMONTH > 0),
  TOTAL numeric(30,2) GENERATED ALWAYS AS (DURATION * CHARGEPERMONTH) STORED,
  PID INTEGER references PRODUCT(PID) NOT NULL
);

CREATE TABLE OWNS(
  GID INTEGER references GARDEN_OWNERS(GID) NOT NULL,
  PID INTEGER references PRODUCT(PID) NOT NULL
);

CREATE TABLE ORDERS(
  OID INTEGER PRIMARY KEY,
  ODATE DATE NOT NULL,
  OAMOUNT INTEGER NOT NULL CHECK (OAMOUNT > 0),
  QUANTITY INTEGER NOT NULL CHECK(QUANTITY > 0),
  PID INTEGER references PRODUCT(PID) NOT NULL,
  CID INTEGER references CUSTOMER(CID) NOT NULL
);


--  danger    WHEN YOUR NEED TO DELETE ALL THE TABLES IN YOUR SCHEMA... DELETE WHOLE SCHEMA AND MAKE IT AGAIN :)
--DROP SCHEMA public CASCADE;
--CREATE SCHEMA public;
--GRANT ALL ON SCHEMA public TO postgres;
--GRANT ALL ON SCHEMA public TO public;
--COMMENT ON SCHEMA public IS 'standard public schema';